name: Takahashi
favicon: null
layout_spectrum: 1
typography_spectrum: 0.18550537154078484
style: the-composer
navigation:
  - id: cd21c1d0-9675-467f-9d6a-450f0d448fcd
    url: >-
      2016-07-19-takahashi-began-manufacturing-telescopes-in-1967-their-35th.html
    name: About Takahashi
    type: content
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#949494'
    - '#125895'
    - '#c7c8e7'
    - '#3591c6'
  brandStrength: 0.6507081449963152
  lightness: 0.09632456908002496
  saturation: 0.7110048227477819
  rhythmicContrast: 0.33009321987628937
purpose: []
