typography_spectrum: 0.18550537154078484
color:
  brandColors:
    - '#020202'
    - '#949494'
    - '#125895'
    - '#c7c8e7'
    - '#3591c6'
  brandStrength: 0.6507081449963152
  lightness: 0.09632456908002496
  saturation: 0.7110048227477819
  rhythmicContrast: 0.33009321987628937
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Takahashi
cta:
  domain: null
  bucket: null
  version: null
style: the-composer
navigation:
  - id: ff551dc2-7b1f-4eee-9ef8-985f53af1996
    url: >-
      2016-07-20-takahashi-began-manufacturing-telescopes-in-1967-their-35th.html
    name: About Takahashi
    type: content
favicon: null
purpose: []
